# Configuración del sitio
title: Sr. Torres Blogs
email: wilberquint455@gamil.com
description: >-
  Blog sobre redes y tecnología. Aprende sobre CCNA, protocolos y más.
baseurl: "/redes" # Cambia esto si tu blog no está en la raíz del dominio
url: "https://wilberquinto455.github.io" # URL de tu sitio
locale: es_ES

# Configuración de URLs
permalink: /blog/:categories/:year/:month/:day/:title/

# Configuración de posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Sr. Torres"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excluir archivos innecesarios
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  - .DS_Store